// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


// Code generated by ragel DO NOT EDIT.
package snmptrap

import (
    "fmt"
)

//line parser.go:8
const syslog_start int = 0
const syslog_first_final int = 2
const syslog_error int = -1

const syslog_en_main int = 0
const syslog_en_catch_all int = 1



var (
	noDuplicates = []byte{'-', '.'}
)

// Parse parses Syslog events.
func Parse(data []byte, event *event) {
	//var p, cs int
	//pe := len(data)
	//tok := 0
	//eof := len(data)
	
	//event.Set
        fmt.Printf("snmptrap log Received!\n")
        
}
